# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "zssd/SYSTEM/NIXOS/rootfs";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BD4E-006F";
    fsType = "vfat";
  };

  fileSystems."/boot-fallback" = {
    device = "/dev/disk/by-uuid/BDE6-9262";
    fsType = "vfat";
  };

  fileSystems."/nix" = {
    device = "zssd/SYSTEM/NIXOS/nix";
    fsType = "zfs";
  };

  fileSystems."/var" = {
    device = "zssd/SYSTEM/NIXOS/var";
    fsType = "zfs";
  };

  fileSystems."/var/docker" = {
    device = "zssd/SYSTEM/NIXOS/var/docker";
    fsType = "zfs";
  };

  fileSystems."/var/lib" = {
    device = "zssd/SYSTEM/NIXOS/var/lib";
    fsType = "zfs";
  };

  fileSystems."/var/lib/libvirt" = {
    device = "zssd/SYSTEM/NIXOS/var/libvirt";
    fsType = "zfs";
  };

  fileSystems."/var/log" = {
    device = "zssd/SYSTEM/NIXOS/var/log";
    fsType = "zfs";
  };

  fileSystems."/var/lxd" = {
    device = "zssd/SYSTEM/NIXOS/var/lxd";
    fsType = "zfs";
  };

  fileSystems."/home/kcrook" = {
    device = "zssd/DATA/HOME/kcrook";
    fsType = "zfs";
  };

  fileSystems."/root" = {
    device = "zssd/DATA/HOME/root";
    fsType = "zfs";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/22d0fd01-915d-4dde-bdae-fbe9327a427a"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
